import Head from 'next/head'
import { getPosts } from '../services'
import Table from '../components/Table'

export default function Home({ posts }) {
 

  
  return (
    <div className="container mx-auto px-15 mb-8">
      <Head>
        <title>Encompass Training</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <Table posts={posts}/>
    </div>
   

  )
}


export async function getStaticProps() {
  const posts = (await getPosts()) || [];

  return {
    props: { posts }
  }
}


