import Head from 'next/head'
import { useSession } from "next-auth/react";
import CourseSelect from '../components/CourseSelect';
import LoginBox from '../components/LoginBox';

export default function Home({ posts }) {

  const { data: session, status } = useSession();
  const loading = status === "loading";
  if (loading) return null;

  if (status === "authenticated") {
    if (sessionStorage.getItem("session")) {
      sessionStorage.removeItem("session")
    }
    sessionStorage.setItem('session', JSON.stringify(session.user.email))
  
  };

  return (
    <div className="container mx-auto px-15 mb-8">
      <Head>
        <title>Encompass Training</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {session ? 
      (<CourseSelect />) : 
      (<LoginBox />)}
    </div>
   


  )
}







